accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView,LoginView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'


urlpatterns = [
    path('signup/',views.SignUpPage.as_view(),name='signup'),
    path('login/',LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='account')),
    path('accounts/',include('allauth.urls')),
    path('accounts/',include('django.contrib.auth.urls')),

    path('user/',include('UserData.urls',namespace='userdata')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User,PermissionsMixin
# Create your models here.

class SignPage(User,PermissionsMixin):

    def __str__(self):
        return '@{}'.format(self.username)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms


class UserForm(UserCreationForm):

    class Meta:
        fields = ('username','email','password1','password2')

        model = get_user_model()

        def __init__(self,*args,**kwargs):

            super().__init__(*args,**kwargs)
            self.fields['username'].label = 'Display Name'
            self.fields['email'].label = 'Email'

accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,CreateView
from django.urls import reverse_lazy
from .forms import UserForm
# from django.contrib.auth.views import PasswordResetView
from django.contrib import messages
# Create your views here.

class HomePage(TemplateView):
    template_name = 'home.html'

class AboutView(TemplateView):
    template_name = 'about.html'

class ContactView(TemplateView):
    template_name = 'contact.html'

class SignUpPage(CreateView):
	form_class = UserForm
	template_name = 'signup.html'
	success_url = reverse_lazy('login')

# class UserPasswordResetView(PasswordResetView):
#     template_name = 'password_reset_form.html'
#     success_url = reverse_lazy('custom_auth:password_reset_done')
#     subject_template_name = 'password_reset_subject.txt'
#     # email_template_name = 'password_reset_email.html'

accounts/templates/about.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}

{% bootstrap_messages %}
{% block title %}

About
{% endblock %}


{% block body %}
<div class="container">
	<h1>Cloud Service</h1>
	<h1>..........</h1>
	<h1>........</h1>
</div>
    
{% endblock %}

accounts/templates/contact.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}

{% bootstrap_messages %}
{% block title %}

Contact
{% endblock %}


{% block body %}
<div class="container">
	<h1>Contact Number</h1>
	<h1>Vivek Singh Adhikari</h1>
	<h1>9968038609<h1>
	<h1>........</h1>
</div>
    
{% endblock %}

accounts/templates/log.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}
Login
{% endblock %}

{% block body %}
    <div class="container">
        {% csrf_token %}
        <h1>SUCESSFULLY LOGIN</h1>

    </div>

{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}
{% load socialaccount %}
{% providers_media_js %}

{% block title %}
Login
{% endblock %}

{% block body %}
    <div class="signbox">
    	<img src="{% static 'images/log.png' %}" class="avatar" >

        <h1>Welcome Back!</h1>
        <form class="formbox" method="POST">
	        {% csrf_token %}
	        {% for error in  bootstrap_form.error %}
	        	<p style="color: red">{{ error }}</p>
	        {% endfor %}
	        {% bootstrap_form form  layout='inline' %}
	        <input type="submit" value="Login">
	        <a class="nav-link p-2" href="{% provider_login_url "google" %}">
	        	<h2>Login With Google</h2>
	        </a>

	        <a href="{% url 'account:password_reset' %}">Forgot Password!</a><br>
            <h7 style="font-size:12px">Don't have an account </h7><a href="{% url 'account:signup' %}">Sign Up</a><h7 style="font-size:12px"> here</h7>
        </form>
    </div>

{% endblock %}

accounts/templates/password_reset_complete.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Reset Complete
{% endblock%}

{% block body %}
<div class="container" style="color: white; font-size: 18px; margin-top: 20px">
	<p>
    	Your password has been set. You may go ahead and <a href="{% url 'account:login' %}">Log In</a> now.
  	</p>
</div>
{% endblock%}

accounts/templates/password_reset_confirm.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}

{% block title %}
Reset Confirm
{% endblock%}

{% block body %}
  {% if validlink %}
    <h1>Change password</h1>

    <form  method="post">
      {% csrf_token %}
      <div class="container" style="color: white; font-size: 18px; margin-top: 20px">
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Change password</button>
      </div>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
{% endblock%}

accounts/templates/password_reset_done.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Reset Done
{% endblock%}

{% block body %}
<div class="container" style="color: white; font-size: 18px; margin-top: 20px">
	<p>
	    We've emailed you instructions for setting your password, if an account exists with the email you entered.
	    You should receive them shortly.
	  </p>
	  <p>
	    If you don't receive an email, please make sure you've entered the address you registered with,
	    and check your spam folder.
	  </p>
</div>
{% endblock%}

accounts/templates/password_reset_email.html
{% load static %}
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} TestSite Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.


Sincerely,
The TestSite Team
{% endautoescape %}

accounts/templates/password_reset_form.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}

{% block title %}
Password Reset forum
{% endblock%}

{% block body %}
<h1>Forgot password</h1>

<form  method="post">
	{% csrf_token %}
	<div class="container" style="color: white; font-size: 18px; margin-top: 20px">
		{{ form|crispy }}
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
</form>
{% endblock%}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}

{% bootstrap_messages %}
{% block title %}

Sign Up
{% endblock %}


{% block body %}
    <div class="signbox">
        <img src="{% static 'images/log.png' %}" class="avatar" >

            <h1>Sign Up for Free</h1>
      	
      	
      		<!-- <div>
      			<h3>Sign Up</h3>
      			<h3>Log In</h3>
      		</div> -->
            <form class="formbox" method="POST">
                {% csrf_token %}
                {% bootstrap_form form layout='inline' %}
                <input type="submit" name="" value="Sign Up">
                <h7 style="font-size:12px">Already have an account </h7><a href="{% url 'account:login' %}">Sign In</a><h7 style="font-size:12px"> here</h7>
            </form>
        </div>
    


{% endblock %}