UserData/urls.py
from django.urls import path
from . import views

app_name = 'user_data'


urlpatterns = [
    path('post_upload/',views.BasicUploadView.as_view(),name='data'),
    path('pic/',views.DisplayImages.as_view(),name='pic'),
    path('detail/<int:pk>',views.UserDataDet.as_view(template_name='details.html'),name='getid'),
    path('edit/<int:pk>',views.UserDetailUpdate.as_view(template_name='userdetailedit.html'),name='edit'),
    path('delete/<int:pk>',views.UserDetailDelete.as_view(template_name='userdelete.html'),name='delete'),

]
# .as_view(template_name='reset/password_reset_form.html')

accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView,LoginView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'


urlpatterns = [
    path('signup/',views.SignUpPage.as_view(),name='signup'),
    path('login/',LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='account')),
    path('accounts/',include('allauth.urls')),
    path('accounts/',include('django.contrib.auth.urls')),

    path('user/',include('UserData.urls',namespace='userdata')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% load static %}
{% load socialaccount %}

<html lang="en">
<head>
    <meta charset="UTF-8">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/formsty.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    <title>{% block title %} {% endblock%}</title>
</head>
<body>
    <div class="main" style="background-image:url({% static 'images/bg-pic.jpg' %})">
     <nav class="navbar navbar-expand-lg navbar-dark" role="navigation"  >
        <div class="container">
            <ul class="navbar-nav bd-navbar-nav flex-row">
                <a class="navbar-brand" href="{% url 'home' %}">Home</a>
                <a class="navbar-brand" id="link" href="{% url 'account:about' %}">About</a>
                <a class="navbar-brand" id="link" href="{% url 'account:contact' %}">Contact</a>
            </ul>
            <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex" >
                {% if user.is_authenticated %}
                    <li class="navbar-brand"><a class="link" href="{% url 'user_data:data' %}">Upload</a></li>
                    <li class="navbar-brand"><a class="link" href="{% url 'user_data:pic' %}">My Data</a></li>
                    
                    <li class="navbar-brand" style="color: black">Welcome: {{user}}</li>
                    <li class="navbar-brand"><a class="link" href="{% url 'account:logout' %}">Logout</a></li>
                    
                {% else %}

                    <li class="navbar-brand"><a class="navbar-brand" href="{% url 'account:signup' %}">Register</a></li>
                   <!--  <a class="nav-link p-2" href="{% provider_login_url "facebook" method="js_sdk" %}">
                        <img src="{% static 'images/fb.jpg' %}" width="30" height="28">
                    </a> -->
                   <!--  <a class="nav-link p-2" href="{% provider_login_url "google" %}">
                        <img src="{% static 'images/goo.png' %}" width="30" height="28">
                    </a> -->
                    <!-- <a class="nav-link p-2" href="#">
                        <img src="{% static 'images/git.png' %}" width="30" height="28">
                    </a>
                    <a class="nav-link p-2" href={% provider_login_url "twitter" method="js_sdk" %}">
                        <img src="{% static 'images/twitter.png' %}" width="30" height="28">
                    </a> -->
                {% endif %}
            </ul>
        </div>
    </nav>

        {% block body %}

        {% endblock %}
    </div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block title %}
HOME
{% endblock%}

{% block body %}

<div class="main_body">
    <h1>Let go into the cloud</h1>
    <p>This website stores your personal data in our cloud database. You can add images,songs,video etc.</p>
</div>
  <a class="buta" href="{% url 'account:login' %}" style="margin-left: 46%"><input type="button" name="Explore" value="Welcome" ></a>

{% endblock%}